GET  http://localhost:5000/api/workspaces HTTP/1.1

###
GET  http://localhost:5000/api/workspaces/status HTTP/1.1

###
POST http://localhost:5000/api/workspaces/abc HTTP/1.1

version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mongo
    ports: ["27017"]

###

POST http://localhost:5000/api/workspace/abc/fork/xyz HTTP/1.1

###

PUT http://localhost:5000/api/workspace/abc/start HTTP/1.1

###

PUT http://localhost:5000/api/workspace/abc/stop HTTP/1.1

### 3001 version node

POST http://localhost:3001/api/workspaces/xyz2 HTTP/1.1
content-type: application/json

{
  "description": "una descripción cualquiera",
  "specification": "'version': '4'"
}

###
PUT http://localhost:3001/api/workspace/xyz2/stop HTTP/1.1

###
PUT http://localhost:3001/api/workspace/xyz2/start HTTP/1.1

###
PUT http://localhost:3001/api/workspaces/xyz2 HTTP/1.1
content-type: application/json

{
  "description": "una descripción cualquiera v2",
  "specification": "version: \"3\"\nservices:\n  db:\n    image: mongo\n"
}