@workspace = yopiyopi

###
PUT http://localhost:3001/api/workspace/{{workspace}}/run HTTP/1.1
content-type: application/json

{
  "specification": "#yopi es mi mejor amigo\nversion: \"3\"\nservices:\n  db:\n    image: mongo\n"
}

###

PUT http://localhost:3001/api/workspace/{{workspace}}/stop HTTP/1.1
content-type: application/json

{
  "specification": "#yopi es mi mejor amigo\nversion: \"3\"\nservices:\n  db:\n    image: mongo\n"
}

